#!/bin/bash

# Screenshot Helper Script
# This script helps you take and organize screenshots for the School Management App

echo "📸 School Management App - Screenshot Helper"
echo "==========================================="
echo ""
echo "This script will help you capture screenshots for the README."
echo ""
echo "Steps to take screenshots:"
echo ""
echo "1. Make sure the app is running on the simulator"
echo "2. Navigate to each screen in the app"
echo "3. Press Cmd+S to save screenshot (saves to Desktop)"
echo "4. Screenshots will be named automatically by iOS"
echo ""
echo "Required Screenshots:"
echo "  ✅ home-dashboard.png - Main dashboard"
echo "  ✅ about-us.png - About section"
echo "  ✅ programs.png - Programs listing"
echo "  ✅ teachers.png - Teachers portfolio"
echo "  ✅ activities.png - Activities list"
echo "  ✅ careers.png - Career opportunities"
echo "  ✅ news.png - News articles"
echo "  ✅ schools.png - Schools directory"
echo "  ✅ contact.png - Contact form"
echo "  ✅ chatbot.png - AI chatbot"
echo "  ✅ admin-login.png - Admin login"
echo "  ✅ more.png - More menu"
echo "  ✅ tab-navigation.png - Tab bar"
echo ""
echo "After taking screenshots:"
echo "1. Move them from Desktop to: $(pwd)"
echo "2. Rename them according to the list above"
echo "3. Run: git add screenshots/"
echo "4. Run: git commit -m 'Add app screenshots'"
echo "5. Run: git push origin main"
echo ""
echo "Tip: You can also use xcrun simctl to automate screenshots"
echo ""
